### PR TITLE
Navbar improvements

### PR DESCRIPTION
**Pull request by JeanVegaD**
# What does this PR do?

- change nav icons on mobile version

### CODE REVIEW

**Comment by xavier506** [comment]
@AngeloCG97  do you now what the status of this ticket is?

**Comment by AngeloCG97** [comment]
Pending icons by Rodolfo

**Comment by xavier506** [comment]
> Pending icons by Rodolfo

is the his still pending?

**Review by xavier506 — APPROVED** [review]
LGTM

**Pull request merged**
